// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal_PrograIII.Data;

#nullable disable

namespace ProyectoFinalPrograIII.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250401062920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Correo_Electronico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nit")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("Id_Proveedor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Proveedor");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_Compras")
                        .HasColumnType("int");

                    b.Property<int>("Id_Productos")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Compras");

                    b.HasIndex("Id_Productos");

                    b.ToTable("DetallesCompra");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_Pedidos")
                        .HasColumnType("int");

                    b.Property<int>("Id_Productos")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Pedidos");

                    b.HasIndex("Id_Productos");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("Id_cliente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Compra", b =>
                {
                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Proveedor", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("Id_Proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.DetalleCompra", b =>
                {
                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Compra", "Compra")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("Id_Compras")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Producto", "Producto")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("Id_Productos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.DetallePedido", b =>
                {
                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Pedido", "Pedido")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("Id_Pedidos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Producto", "Producto")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("Id_Productos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Pedido", b =>
                {
                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Compra", b =>
                {
                    b.Navigation("DetallesCompra");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Pedido", b =>
                {
                    b.Navigation("DetallesPedido");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Producto", b =>
                {
                    b.Navigation("DetallesCompra");

                    b.Navigation("DetallesPedido");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Proveedor", b =>
                {
                    b.Navigation("Compras");
                });
#pragma warning restore 612, 618
        }
    }
}
